[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "https://api.yumi77965.online"
  VITE_FRONTEND_URL = "https://yumi77965.online"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://api.yumi77965.online"
  
[context.deploy-preview.environment]
  VITE_API_URL = "https://api-staging.yumi77965.online" 