# .github/workflows/deploy-frontend.yml
name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  pages: write         # allow the deploy step
  id-token: write      # not strictly needed here, but good practice

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies & build
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: frontend/dist

  deploy:
    needs: build-and-upload
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
